
version = 1
[install]
hello.pkg-path = "hello"

[build]
mypkg.description = "Some sample package description from our tests"
mypkg.version = "1.0.2a"
mypkg.license = ["my very private license"]
mypkg.command = """
    mkdir -p $out/bin
    echo -n "!#/bin/sh" > $out/bin/mypkg
    echo -n "echo Happy Floxing!" > $out/bin/mypkg
    chmod +x $out/bin/mypkg
"""

mypkg_missing_fields.command = """
    mkdir -p $out/bin
    echo -n "!#/bin/sh" > $out/bin/mypkg2
    echo -n "echo Happy Floxing!" > $out/bin/mypkg2
    chmod +x $out/bin/mypkg2
"""

