# One CLI to format the code tree - https://git.numtide.com/numtide/treefmt

[formatter.nix]
# Formatter to run
command = "nixfmt"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.nix" ]
# Glob patterns of files to exclude
excludes = []


[formatter.yaml]
# Formatter to run
command = "yamlfmt"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.yml", "*.yaml" ]
# Glob patterns of files to exclude
excludes = [ "test_data/**" ]
