[package]
name = "runix"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
derive_more = "0.99.17"
tokio = { version = "1.21", features = ["full"] }
log = "0.4.17"
thiserror = "1.0"
serde = "1.0"
serde_json = "1.0"
