[package]
name = "flox-rust-sdk"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"]}
config = "0.13.1"
anyhow = "1.0.65"
tokio = { version = "1", features = ["full"] }
rnix = "0.11"
serde = "1.0"
serde_json = "1.0"
octocrab = "0.17.0"
dotenv = "0.15.0"
async-trait = "0.1.52"
getset = "0.1.2"
log = "0.4.17"
pretty_env_logger = "0.4.0"
derive_more = "0.99.17"
derive_builder = "0.11.2"
runix = {path = "../runix"}
url = "2.3" # 2.3.1 has conflicting dependencies with octocrab
serde_with = "2.0.1"
thiserror = "1.0"
nix-editor = "0.2.12"
tempfile = "3.3.0"
fs_extra = "1.2.0"
regex = "1"
once_cell="1.16.0"
