[package]
name = "flox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flox-rust-sdk = { path = "../flox-rust-sdk" }
anyhow = "1.0.65"
tokio = { version = "1", features = ["full"] }
rnix = "0.10.2"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
git2 = "0.15.0"
octocrab = "0.17.0"
dotenv = "0.15.0"
async-trait = "0.1.52"
log = "0.4.17"
bpaf = { version = "0.7.6", features = ["derive", "autocomplete"] }
config = "0.13.1"
dirs = "4.0.0"
tempfile = "3.3.0"
futures = "0.3.25"
once_cell = "1.16.0"
serde_variant = "0.1.1"
itertools = "0.10.5"
regex = "1"
supports-color = "1.3.1"
inquire = { git = "https://github.com/flox/inquire.git" }
crossterm = "0.25"
shell-escape = "0.1.5"
xdg = "2.4"
nix = "0.26"
indoc = "1.0"
derive_more = "0.99.17"
time = { version = "0.3", features = ["serde"] }
uuid = { version = "1.2", features = ["serde", "v4"] }
reqwest = "0.11"
sys-info = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = { version = "0.1", features = ["env_logger"] }
fslock = "0.2.1"
indexmap = {version =  "1.9", features = ["serde"] }

[features]
extra-tests = ["bats-tests", "impure-unit-tests"]
impure-unit-tests = []
bats-tests = []
